### ISSUE TITLE
有问题，会重复导出相同的文件出来

### ISSUE THREAD

**Issue by WTepiphany** [jiongjiongJOJO/telegram_info_export#2]
一开始导出的时候需要验证码，后面不用，但是导出的数据也是一样的一直再重复

**Comment by jiongjiongJOJO** [comment]
同一个账号吗？还是多个账号导出的结果一样？

**Comment by WTepiphany** [comment]
肯定不是同一个账号啊，我导了好几个，从第三个开始就一直在重复导出的第二个结果

**Comment by jiongjiongJOJO** [comment]
删除程序目录的session文件再试试呢？

**Comment by WTepiphany** [comment]
我刚刚删了session后重新导了两个号可以，但是导新号的时候必须删掉旧的session

**Comment by jiongjiongJOJO** [comment]
你可以使用不一样的API Name，生成的应该就是不同的session了

**Comment by WTepiphany** [comment]
可能是这个原因，我用的都是相同的name。主要是方便

**Comment by jiongjiongJOJO** [comment]
多账号登陆导出文件相同的问题已经解决，请确认该问题是否仍然存在。详情请查看 [v1.1.0](https://github.com/jiongjiongJOJO/telegram_info_export/releases/tag/v1.1.0)。
如果还有问题，请重新提交issue。
